### ISSUE TITLE
Seren errors on Kodi Startup

### ISSUE THREAD

**Issue by 416eddie** [nixgates/plugin.video.seren#112]
Hi
My Kodi is crashing on startup and when it doesn’t crash it gives me check log file. 
I am using Seren 0.2.24 on Kodi 18.2 a fresh install of Kodi and Seren last night did not fix. Here is the log file. 

https://pastebin.com/WxEck7T4

**Comment by drinfernoo** [comment]
```2019-05-04 16:03:50.446 T:123145327259648   ERROR: CAddon[plugin.video.seren]: unable to load: /Users/[username]/Library/Application Support/Kodi/addons/plugin.video.seren/resources/settings.xml, Line 0

                                            Failed to open file

2019-05-04 16:03:50.491 T:123145327259648   ERROR: Previous line repeats 1 times.

2019-05-04 16:03:50.491 T:123145327259648   ERROR: Traceback (most recent call last):

2019-05-04 16:03:50.491 T:123145327259648   ERROR:   File "/Users/[username]/Library/Application Support/Kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 854, in is_aired

2019-05-04 16:03:50.493 T:123145327259648   ERROR:   File "/Users/[username]/Library/Application Support/Kodi/addons/plugin.video.seren/resources/lib/common/tools.py", line 559, in gmt_to_local

2019-05-04 16:03:50.493 T:123145327259648   ERROR:   File "/Users/[username]/Library/Application Support/Kodi/addons/plugin.video.seren/dateutil/tz.py", line 933, in gettz

2019-05-04 16:03:50.493 T:123145327259648   ERROR: ImportError: No module named zoneinfo

```

**Comment by nixgates** [comment]
Looks like something is wrong with your Seren install weirdly enough.

**Comment by 416eddie** [comment]
Hi
There is a folder by that name and it has the following in it
_int_.py
_int_.pyo
GMT
temp.gz
zoneinfo-2010g.tar
Thanks for following up with me on this

**Comment by nixgates** [comment]
@416eddie 

can you just confirm for me that the file is named int or is it "__init__.py"?

**Comment by 416eddie** [comment]
One file is  _int_.py  and another called _int_.pyo

**Comment by 416eddie** [comment]
When ever I type it in it takes the _ out not sure why that is the file is _int_.py

**Comment by 416eddie** [comment]
My auto correct keeps changing the init to int too but the file is definitely _init_.py

**Comment by drinfernoo** [comment]
It's called `__init.py__`.

**Comment by 416eddie** [comment]
There is no_ after the .py

**Comment by drinfernoo** [comment]
@416eddie Fixed it, my bad.

**Comment by 416eddie** [comment]
Thanks

**Comment by nixgates** [comment]
Lol Github formatting killing the conversation.

@416eddie is the issue still there after the latest update?

**Comment by 416eddie** [comment]
Yes the issue is still there but I was going to try to uninstall and reinstall completely to see if that fixes it, I will let you know once if have had time to do that, thanks for keeping up on this

**Comment by 416eddie** [comment]
I have reinstalled and it seems to be working fine now. Thanks for the help.

**Comment by 416eddie** [comment]
Spoke too soon I was able to turn off Kodi and trim it back on with out issue twice then I had to shut it down one other time now having the same issue with Seren error message and Kodi just shuts down with in 30 seconds of start up plus now I am unable to authorize real debrid

**Comment by nixgates** [comment]
Did you reinstall Kodi or Seren?

**Comment by 416eddie** [comment]
I just reinstalled Seren I might try a full reinstall of Kodi on the weekend

**Comment by 416eddie** [comment]
Here is a new log file 
https://pastebin.com/nmBBuDfg

**Comment by nixgates** [comment]
Issue should be fixed come next update :)

**Comment by nixgates** [comment]
@416eddie could you please check and confirm the issue is now resolved with 0.2.35?

**Comment by 416eddie** [comment]
Still having the issue will try do a fresh install of Seren tomorrow and see if that works

**Comment by 416eddie** [comment]
Here is a new log file

https://pastebin.com/sF003nhB

**Comment by 416eddie** [comment]
Did a fresh install of Kodi 18.2, fresh install of Bingie skin, and Seren Addon and still having the same issue. The only way I can keep it from crashing is to navigate away from the home screen and get to some setting menu like Addon browser, but most of the time it crashes before I can get there so it takes about 10 tries before I can get it launched and stay launched.  Here is the latest log file 
https://pastebin.com/77R3H6h5

**Comment by nixgates** [comment]
Looking at your log, this is a whole new kind of issue where previously you were having issues with the dateutils package, now you are experiencing errors all over the place with not only multiple addons but core kodi packages as well.

Skin Helper Addon:
> File "/Users/[username]/Library/Application Support/Kodi/addons/script.skin.helper.backgrounds/resources/lib/smartshortcuts.py", line 200, in playlists_nodes
                                            ImportError: No module named ElementTree

Seren:
>  File "/Users/[username]/Library/Application Support/Kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/__init__.py", line 349, in _get_connection
2019-05-25 12:49:07.947 T:123145761165312   ERROR:     conn = db.connect(database_path, timeout=60.0)
2019-05-25 12:49:07.947 T:123145761165312   ERROR: OperationalError: unable to open database file

Core Kodi Modules:

> File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/socket.py", line 191, in __init__
                                            error: [Errno 24] Too many open files

Netflix:

> File "/Users/[username]/Library/Application Support/Kodi/addons/plugin.video.netflix/service.py", line 243, in <module>

Exodus Redux:

> IOError: [Errno 24] Too many open files: '/Users/[username]/Library/Application Support/Kodi/addons/plugin.video.exodusredux/default.py'

My suggestion to you would be to do a clean install again, stick to the standard skin and install addons one at a time until the issue presents itself. If you start getting an issue after you install an addon/skin try again without that addon/skin.

As this is no longer a Seren specific issue I would suggest you look at removing all any blacklisted addons and then raising an issue on the official Kodi forum with a new debug log.

**Comment by 416eddie** [comment]
Hi
Ok thanks for the suggestion.

**Comment by 416eddie** [comment]
I have done a fresh install of everything and still the same issue when I load Seren unless I unlock hubs in the skin setting and leave them unlocked, then it launches fine but still get Seren error. One thing I noticed with a fresh install when I go to Tool/Premium Services/Current Real Debrid Transfers there is a whole list of files there some marked dead some marked error some marked magnet conversion with 0% and some marked downloaded. It won’t let me delete these and I have tried wipe Addon data and reset settings and go back to this menu and the list appears again.

**Comment by 416eddie** [comment]
Latest log file https://pastebin.com/z9p2Ytbz

**Comment by nixgates** [comment]
I'm going to try and get my hands on an Apple TV this weekend and have a look.

The Apple TV is doing a lot of weird things that I'm really going to have to look at personally.

**Comment by 416eddie** [comment]
Hi
Thanks for continuing to look at this but I am using a Mac mini not Apple TV, although I have read some posts on other sites about issues with Apple TV and Kodi 18.2. It may have something to do with the way macs deal with file structure and permissions.

**Comment by nixgates** [comment]
@416eddie yea it's possible.

I have an update in the works that might help in this situation if the issue is the same as the Apple TV issue.

**Comment by 416eddie** [comment]
Hi
Great I look forward to trying it out. 

Thanks
Ted

**Comment by nixgates** [comment]
This issue should be resolved with the new update.

Could you please check and confirm @416eddie

**Comment by 416eddie** [comment]
Hi
I will try a fresh install of everything but still having the issue with just updating the existing install. Plus there is a Kodi update that I just updated so will have to dump everything tomorrow and do a fresh install of everything and get back to you. 
Thanks for checking back in this issue.

**Comment by 416eddie** [comment]
Hi
This is all working as it should now, no more crashing or error messages. Thanks for the help it is much appreciated.
