### ISSUE TITLE
Next Up Won't Load - Ver1.4.6

### ISSUE THREAD

**Issue by hockeymachine86** [nixgates/plugin.video.seren#167]
When you go to "My TV Shows" > "Next Up", it shows up blank.  The log file has the following error

> 18:20:44.364 T:140564983568128   ERROR: Traceback (most recent call last):
> 18:20:44.364 T:140564983568128   ERROR:   File "/storage/.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 675, in mixedEpisodeBuilder
> 18:20:44.365 T:140564983568128   ERROR:     reverse=True)
> 18:20:44.365 T:140564983568128   ERROR: TypeError: can't compare datetime.datetime to NoneType

**Comment by hockeymachine86** [comment]
Here is full debug log:
https://pastebin.com/6anqG1Lw

**Comment by nixgates** [comment]
I've just pushed a hotfix which should include a fix for this. Could you please test and confirm? 😊

**Comment by hockeymachine86** [comment]
Tried to update to 1.4.7 and get this error
21:46:25.071 T:140570043344640   ERROR: CAddonInstallJob[plugin.video.seren]: invalid package special://home/addons/packages/plugin.video.seren-1.4.7.zip

**Comment by DJMix-I-Can** [comment]
It's still not working on a Fresh Install... I didn't get an update notification and tried to force the update, nothing. I just wound up downloading the zip file.
Here goes the debug file.
https://pastebin.com/hQtk6cYS

**Comment by hockeymachine86** [comment]
I couldn't get the update to work by checking for updates from the repo, but was able to update by downloading zip file and installing from that. 
Update **does** fix the Next Up not loading isssue.

**Comment by drinfernoo** [comment]
@hockeymachine86 No, the repo install issue should be fixed shortly.
