### ISSUE TITLE
Seren 2.0.6 throws Trakt Error but Trakt is not authorized nor needed.

### ISSUE THREAD

**Issue by jweinreich** [nixgates/plugin.video.seren#277]
New error since updating to 2.0.6, "Unknown error while connecting to trakt"
But I haven't and don't need to use trakt on seren.

Log:

https://paste.kodi.tv/wejurumiku.kodi

Thanks

**Comment by drinfernoo** [comment]
Seren uses Trakt whether you do or not.

**Comment by nixgates** [comment]
Apologies but this is due to a connection error between yourself and Trakt. 

As @drinfernoo mentioned, Seren uses Trakt as a base for all it's menus whether an account has been created or not.

Closing issues

**Comment by jonypaulo** [comment]
It's happening exactly the same with me,  already updated to 2.0.8 and wiped addon data and it continues to do the same. 
Yesterday was functioning perfectly before i updated today...

**Comment by jonypaulo** [comment]
Problem fixed 

After many attempts i realuzed that after the last update seren appears like a new addon,  so i had to add it again in the filter of the vpn service to pass to it. 

Problem solved and i leave here the solution for the ones having the same problem 👌🏻

**Comment by jweinreich** [comment]
Thanks for your response Nix,

I can connect normally to trakt with the official trakt addon, everything just works.
I have now authorized Seren with trakt but the error remains.
I have tried disabling the trakt addon just to see if there was some conflict.
Only Seren 2.0x shows this behaviour. Previous version had no errors with trakt whatsoever, having authorized trakt or not.
In the case you are willing to dig into this further, I'm available for testing.

`2021-01-03 13:05:14.337 T:30920   ERROR: SEREN: Connection Error to Trakt: (<resources.lib.indexers.trakt.TraktAPI object at 0x25ad6c9ca0>,) - {'url': u'sync/last_activities'}
2021-01-03 13:05:14.337 T:30920   ERROR: SEREN: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /sync/last_activities (Caused by ResponseError('too many 500 error responses',))
2021-01-03 13:05:14.338 T:30920   ERROR: SEREN: Background service failure
`

**Comment by jweinreich** [comment]
Updated to Seren 2.0.8 and error is gone.

**Comment by nixgates** [comment]
@jweinreich good to hear mate!

**Comment by jonypaulo** [comment]
Updated to 2.0.9 and error is back and everytime i restart the program resets all acounts (trakt, realdebrid, premiumize, etc.) :(

**Comment by jweinreich** [comment]
> Updated to 2.0.9 and error is back and everytime i restart the program resets all acounts (trakt, realdebrid, premiumize, etc.) :(

Working fine on my end.
Did you try wiping the addon again?

**Comment by jonypaulo** [comment]
I did a wyping and uninstalled and installed again. 
After 3 wipings looks that it is working, even giving the same error, the traktor things appear. 
Lets see if it continues

**Comment by jweinreich** [comment]
Did you authorize Trakt on Seren app?
Are your accounts (RD, PM etc) fine now?

**Comment by jonypaulo** [comment]
> Did you authorize Trakt on Seren app?
> Are your accounts (RD, PM etc) fine now?

I did autorize all of them already 8 times. 
Every single time it ends up to reset the setting of the app and i have to authorize everything again... 
Before this updates it was working perfectly :(

**Comment by jonypaulo** [comment]
And now after i uninstalled and installed again i can't even put the accounts. 
Everytime i confirm any of them gives error

**Comment by KeKyKo** [comment]
This is also happening to me.  Im using Seren 2.0.10, I cannot log into Trakt.  When I try I get a popup that says, "Unable to contact Trakt. Please check Trakts outage status at: HTTP//status.trakt.tv"  I have un installed Seren, I have cleared cache.  Nothing works.  I am able to authorize Real-Debrid & Premiumize.me.  Help.

**Comment by nixgates** [comment]
This is resolved in 2.0.11+

Apologies for this.

**Comment by KeKyKo** [comment]
THANK YOU!!! FOR AN AMAZING ADD-ON :)

**Comment by RichardManciniJr** [comment]
I just downloaded .12 and I'm getting errors trying to add provider info... still getting Seren errors as well. App and data was wiped.

**Comment by nixgates** [comment]
@RichardManciniJr please raise a new incident

**Comment by RichardManciniJr** [comment]
> @RichardManciniJr please raise a new incident

It somehow righted itself. I reauthorized Prem and RD, and it reset my Trakt authorization 2x. Everything worked once I reauthorized the 2nd time. Everything seems to be working perfectly now. Thanks for all the hard work.
