### ISSUE TITLE
Won't play hoster files - real debrid

### ISSUE THREAD

**Issue by biscuitgod** [nixgates/plugin.video.seren#307]
After the Seren 2.0.6 update today, any source that is a hoster will not play. No error, just takes me back to previous screen. From playing around a bit, I have figured out that all torrent sources seem to play just fine. 

I'm using Real-Debrid and it's up to date and current. 
Provider file is a4kscrapers.   I have tried to re-authorize Real Debrid and while the authorization process works, no change in behavior.  

I've tested with the following shows:   Devs s1e5 (just watched s1e4 this morning before update via hoster), great Christmas light fight (s8e6), and bachelorette (s16e13).

Updated to latest today - 2.0.8 - same behavior.  Only thing I haven't tried yet is resetting the Seren add-on completely, which I'm not against but would rather wait as a last resort for this.

**Comment by nixgates** [comment]
@biscuitgod I can't replicate this issue, would you mind providing me a log of the resolve failures?

**Comment by biscuitgod** [comment]
I replicated this on my PC - brand new install from scratch.

Only seren changes I made were (aside from adding provider -a4kscrapers- Trakt and Real Debrid accounts):
1.  In settings, under Scraping > Terminate on... - Changed to Hosters Only
2.  In Settings, under Sort & Filter > Source grouping style - Changed to No Grouping
3.  In Settings, under Playback > Movie & Episode Play Style - Changed to Source Select

I tested with Devs s1e8, but have seen it on countless other shows as well.   I am aware that hosters are going to the wayside here or have been for some time, but strange enough, I have found some shows where there isn't much of a Torrent selection at all - and when those don't work, I'm left with nothing.

Log is available here:  https://paste.kodi.tv/ujelawogoq.kodi

I believe the scraping and playback happens around line 1000 or so - but I am limited in my ability to read this thing, so it's just a guess.

Thanks!

**Comment by biscuitgod** [comment]
With the release of 2.0.9, I am now getting a error - No playable sources found for item.   I was getting no error prior.

**Comment by nixgates** [comment]
@biscuitgod looks like the head request to the file is timing out. I will try those files myself and get back to you.

That head request is a further insurance to make sure the file is alive but it could be timing out to quickly.

**Comment by nixgates** [comment]
@biscuitgod I've identified the issue, these files are incorrectly showing in the source select when they are not playable. 

This will be fixed in next update.

**Comment by biscuitgod** [comment]
@nixgates Awesome!   Thanks for all the work you do on this!

**Comment by nixgates** [comment]
@biscuitgod this should be fixed now. Can you confirm for me please?

**Comment by biscuitgod** [comment]
@nixgates 

negative - issues still occurring.    I am no longer getting the error about playable sources.   When I click a hoster in the source select screen, it acts like it plays but then takes me back to the episode screen prior to scraping.

The upgrade to 2.0.12 went fine, I did need to reauthorize Trakt and then rebuild database.   My first test yielded a YouTube error, which i had to take a screen capture to peg down the 1 or 2 frames it appeared on the screen for.   Turns out i needed to setup my own API?   This was new to me, but got that done and functioning.

I tested on Mandalorian s1e5 to make sure i had a common enough show that would yield decent results.

Log here:  https://paste.kodi.tv/dibimisiwo.kodi

Let me know if you need me to test anything else or make any changes.    I am testing on my clean PC build and easily wipe and ensure a fresh install if needed, however, it's fairly clean as is.

Thanks!!

**Comment by nixgates** [comment]
@biscuitgod I've dug into this a bit deeper and looks like there was an issue with how Seren was handling hoster sources. This should be resolved now in the next update :+1:

Tested and confirmed on my end, once it's released can you give it a go?

**Comment by nixgates** [comment]
@biscuitgod I'm gonna close this one off, I can no longer replicate the issue on the latest version.

If you're still having issues on 2.0.15+ let me know :)

**Comment by biscuitgod** [comment]
@nixgates was out for the the last week, but I have confirmed this is now functional - sorry if this post re-opens.
