### ISSUE TITLE
UpNext

### ISSUE THREAD

**Issue by icpryde** [nixgates/plugin.video.seren#37]
Hey Nix, quick thing I noticed with Using UpNext and NextUp together.

So if you let UpNext either time out and auto play the next episode OR click “play” so it starts the next episode. What ends up happening is it will immediately mark on Trakt the new episode as “watched” even if you stop it right away. So NextUp will show the next episode.

In other words if I use UpNext to start the next episode (episode 8) then immediately stop the episode. NextUp will show episode 9 and trakt will mark episode 8 as watched.

I can provide logs just let me know which ones?

**Comment by nixgates** [comment]
I'm assuming this issue is on 18?

This has been caught and should be rectified in next update.

The issue is Kodi appears to be delaying updating its time info so when Seren sends info to trakt it's actually sending the time info for the previous playlist item so it gets marked as watched.

**Comment by icpryde** [comment]
Oh awesome 👍🏽 , ya it’s on 18.

**Comment by nixgates** [comment]
@icpryde 

Can you check and confirm the issue is resolved?

**Comment by icpryde** [comment]
@nixgates thanks so much for the fix! I’m on my way home so I’ll check as soon as I get there.

**Comment by RagnarLothbrok-Odin** [comment]
Still broken to me, I have a theory though so would love your input.
This picture has episode 19 marked as watched, however, I only just started it and I am only 4 seconds in legit.
![b7726145df00f837e1af31f7b422deb9](https://user-images.githubusercontent.com/30740511/53057963-3718cb80-34a9-11e9-8606-ad5e1ddb5950.png)
Now this photo is from Trakt, my theory is, it's marking it as watched when you start the episode, but also checking in, so when the episode ends, the check in ends and it marked again.
![3040813e73ceae9604b27c1f41a0dff4](https://user-images.githubusercontent.com/30740511/53058007-5dd70200-34a9-11e9-867c-6c826c21fc21.png)

**Comment by RagnarLothbrok-Odin** [comment]
![f2ebeeaab0ff21493a7d6ae22250d655](https://user-images.githubusercontent.com/30740511/53058235-346aa600-34aa-11e9-9774-da28906cd592.png)
The times even match, I started the episode at 00:02 and it ended at 00:42

**Comment by icpryde** [comment]
@nixgates the update doesn’t seem to be available in the repo even if I click check for updates?

**Comment by RagnarLothbrok-Odin** [comment]
There isn't an update lol

**Comment by icpryde** [comment]
Oh I’m an idiot, I thought this was a response to my other ticket that I opened.

I’m watching an episode now and will see after it’s done if it works as intended.

**Comment by icpryde** [comment]
crap, trying to test next up but i keep getting errors today not sure if its just trakt is down? it seems to be working for me with other addons currently.

I keep getting this error now @nixgates 

https://i.imgur.com/BVcbXaO.jpg

**Comment by icpryde** [comment]
Heres my logfile I'm getting quite a few errors which I think is from trakt but not sure?

http://paste.kodi.tv/qejugatuco

**Comment by icpryde** [comment]
@nixgates it didn’t fix the issue, I started episode 3 using UpNext then was only 1 minute into the show and stopped it. Trakt still marked episode 3 as watched and went to episode 4.

**Comment by Mastacc** [comment]
Yea, this is still very glitchy. Sometimes the episode you're watching doesn't even get marked, but the next one does. The next episode seems to always be marked as watched as soon as it starts. Also, the timing is weird. The next episode is marked watched before the current episode.

Scenario 1 (more common):
1x09 ends at 8:29:59
1x10 marked watched at 8:29
1x09 marked watched at 8:30

Scenario 2 (timing irrelevant, less common):
1x09 ends
1x10 marked as watched
(1x09 is never matched as watched)

Seems the auto marked watched from scrobbling is very wonky which is strange because it was perfect before Leia.

**Comment by icpryde** [comment]
Ya try it yourself Nix, opens show you are currently watching by clicking it in the UpNext list. Then when the episode is finishing and the drop down (NextUp) comes up asking you to watch the next episode click “watch now” let the episode start and then just stop the episode like 30 second or a minute in and after a few minutes UpNext will skip the episode you just started and mark it as watched and show the next episode.


Also sorry if I’m getting UpNext and Next Up mixed up those names are way to similar lol.

**Comment by babz1989** [comment]
I'm also having this issue on latest seren version. I'm using shield tv kodi 18.1 and getting multiple markings for episodes when using the upnext feature

**Comment by nixgates** [comment]
@babz1989 could you identify which version of Seren you mean by latest?

Are you running version 0.2.24?

**Comment by babz1989** [comment]
@nixgates This issue has been fixed for me with the latest updates
