### ISSUE TITLE
[BUG] Sorting issue w/ Trakt lists.

### ISSUE THREAD

**Issue by Dealz-416LS** [nixgates/plugin.video.seren#561]
**Logs**
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6214822/kodi.log)

**Describe the bug**
1. My created lists on Trakt are stuck in `Rank` sorting on Seren, I have the default sorting on Trakt set to `Recently Watched` for 1 of the lists but in Seren the sorting is `Rank`.

2. Liked Trakt lists that are sorted by `Rank` so rank number 1, first (Ascending) will be backwards in Seren rank number 250 first (Descending).

**To Reproduce**
1. Create a list on Trakt, add shows to the list, change default sorting to `Recently Watched`, Seren won't honour that sorting and instead will sort by `Rank`.
2. Like a Trakt list that is sorted by `Rank` i.e Top 10, Top 250 etc, The highest ranked item (number 1) will be first on Trakt however that same item in Seren will be last due to sorting being backwards (Descending). 

**Expected behavior**
1. Seren should honour the default sorting of a Trakt list including Ascending or Descending.

**Screenshots**
N/A

**Kodi Version (please complete the following information):**
 - Kodi Version 19.0
 - Seren Version 2.0.18

**Additional context**
N/A

**Comment by drinfernoo** [comment]
This should already be happening... Have you created or modified the sorting of these lists *after* Seren has synced them?

Also, please attach a debug log as requested by the bug report template.

**Comment by Dealz-416LS** [comment]
> 
> 
> This should already be happening... Have you created or modified the sorting of these lists _after_ Seren has synced them?
> 
> Also, please attach a debug log as requested by the bug report template.

Not initially no, but yes i modified the sorting while i was trying to get it to work, I changed the default sorting to `Title` as a test but it still sorts as `Rank` on Seren.

Log added.

**Comment by Dealz-416LS** [comment]
Custom personal lists don't update at all now, If i add an item to a custom list via Trakt website it doesn't show up in Seren even after a Force Sync and Database rebuild.

**Comment by drinfernoo** [comment]
Well, nothing has changed in Seren...

**Comment by Dealz-416LS** [comment]
Update: 

Re-Tested on 2.0.19 still experiencing both issues from original post including recent comment of custom lists not updating on Seren after adding new items to a list on Trakt.

**Comment by Dealz-416LS** [comment]
Update:

Re-tested on 2.1.0 after a cache clear and database rebuild, still experiencing both issues reported above.

1. My personal list is still being sorted using `Rank` when i have it set with default sorting `Recently Watched` on Trakt.
2. Liked Trakt list e.g. Top Rated are in Descending order (backwards) so item 1# is last instead of first.

**Comment by drinfernoo** [comment]
I can reproduce both of these bugs.

**Comment by drinfernoo** [comment]
I can confirm this has been fixed in dev... should be working in the next update :+1:

**Comment by drinfernoo** [comment]
This one should be fixed as of 2.1.2.

**Comment by Dealz-416LS** [comment]
Issue 1: This is still an issue but the reason (confirmed by @drinfernoo) is because the sort type "Recently Watched" which can be set on the Trakt website isn't sorted by Seren.

I have opened a feature request #642 so it can hopefully get added to the list of sort types already supported.

Issue 2: This is fixed 2.1.2
I have checked several user lists that are ranked e.g. Top 250 and all were sorted in the correct order (ascending).
