### ISSUE TITLE
[BUG] Everytime kodi is started, Seren logs an error in kodi.log

### ISSUE THREAD

**Issue by peno64** [nixgates/plugin.video.seren#574]
**Logs**

https://paste.kodi.tv/ahajamobiw.kodi

**Describe the bug**

Everytime kodi start up the following error appears in the log:

2021-03-20 08:27:53.591 T:998     ERROR <general>: SEREN: Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.seren/service.py", line 47, in <module>
                                                       maintenance.run_maintenance()
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/common/maintenance.py", line 276, in run_maintenance
                                                       ProviderInstallManager()
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/providers/install_manager.py", line 41, in __init__
                                                       super(ProviderInstallManager, self).__init__()
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/providers/__init__.py", line 49, in __init__
                                                       self._init_providers()
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/providers/__init__.py", line 56, in _init_providers
                                                       self.update_known_providers()
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/providers/__init__.py", line 102, in update_known_providers
                                                       all_providers = providers.get_all(self.language)
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providers/__init__.py", line 64, in get_all
                                                       return _get_providers(language)
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providers/__init__.py", line 44, in _get_providers
                                                       provider_list = __import__(providers_path, fromlist=[''])
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providers/a4kScrapers/__init__.py", line 3, in <module>
                                                       from providers.a4kScrapers.en import get_torrent, get_hosters
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providers/a4kScrapers/en/__init__.py", line 3, in <module>
                                                       from . import torrent
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providers/a4kScrapers/en/torrent/__init__.py", line 3, in <module>
                                                       from providerModules.a4kScrapers import core
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/core.py", line 15, in <module>
                                                       from .urls import trackers, hosters, get_urls, update_urls, deprioritize_url
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/urls.py", line 73, in <module>
                                                       trackers = _get_urls_in_array_format(trackers_config)
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/urls.py", line 65, in _get_urls_in_array_format
                                                       cached_urls = _get_cached_urls(scraper)
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/urls.py", line 21, in _get_cached_urls
                                                       cache_result = database.cache_get(cache_key)
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/database.py", line 14, in cache_get
                                                       return g.CACHE.get(key)
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/database/cache/__init__.py", line 150, in get
                                                       result, expires = self._db_cache.get(cache_id, checksum)
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/database/cache/__init__.py", line 282, in get
                                                       cache_data = self.execute_sql(query, (cache_id,)).fetchone()
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 228, in execute_sql
                                                       return self._execute_query(data, connection.cursor(), query)
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 178, in _execute_query
                                                       result = cursor.execute(query, data)
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 81, in _loads
                                                       return pickle.loads(g.encode_py2(value))
                                                   _pickle.UnpicklingError: invalid load key, '['.

I tracked it down to this code in resources\lib\database\__init__.py

    @staticmethod
    def _loads(value):
        """ Depickling method.

        :param value:Bytes with the pickled object
        :type value:str|bytes
        :return:Depickled value
        :rtype:any
        """
        if value is None:
            return None

        retries = 0
        while retries < 2:
            try:
                return pickle.loads(g.encode_py2(value))
            except pickle.UnpicklingError:
                return None
            except RuntimeError:
                retries += 1
                continue

When I change it to:

    @staticmethod
    def _loads(value):
        """ Depickling method.

        :param value:Bytes with the pickled object
        :type value:str|bytes
        :return:Depickled value
        :rtype:any
        """
        if value is None:
            return None

        retries = 0
        while retries < 2:
            try:
                return pickle.loads(g.encode_py2(value))
            except pickle.UnpicklingError:
                return None
            except RuntimeError:
                retries += 1
                continue
            except:
                return None

The problem is solved. 

According  to https://docs.python.org/3/library/pickle.html it is possible to get other errors than pickle.UnpicklingError:

"Note that other exceptions may also be raised during unpickling, including (but not necessarily limited to) AttributeError, EOFError, ImportError, and IndexError."

**To Reproduce**
1. Start kodi

**Expected behavior**

No errors should be in kodi.log

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 19.0 (LibreElec 9.95.1)
 - Version 2.0.17+matrix.1

**Comment by drinfernoo** [comment]
This should be fixed in 2.0.18.

**Comment by peno64** [comment]
@drinfernoo 
I installed version 2.0.18+matrix.1 and the same error still occurs:

2021-03-26 22:51:15.589 T:1137    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class '_pickle.UnpicklingError'>
                                                   Error Contents: invalid load key, '['.
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.seren/seren.py", line 19, in <module>
                                                       router.dispatch(g.REQUEST_PARAMS)
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 754, in dispatch
                                                       ProvidersServiceManager().run_long_life_manager()
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/providers/service_manager.py", line 20, in __init__
                                                       super(ProvidersServiceManager, self).__init__()
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/providers/__init__.py", line 48, in __init__
                                                       self._init_providers()
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/providers/__init__.py", line 55, in _init_providers
                                                       self.update_known_providers()
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/providers/__init__.py", line 101, in update_known_providers
                                                       all_providers = providers.get_all(self.language)
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providers/__init__.py", line 64, in get_all
                                                       return _get_providers(language)
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providers/__init__.py", line 44, in _get_providers
                                                       provider_list = __import__(providers_path, fromlist=[''])
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providers/a4kScrapers/__init__.py", line 3, in <module>
                                                       from providers.a4kScrapers.en import get_torrent, get_hosters
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providers/a4kScrapers/en/__init__.py", line 3, in <module>
                                                       from . import torrent
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providers/a4kScrapers/en/torrent/__init__.py", line 3, in <module>
                                                       from providerModules.a4kScrapers import core
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/core.py", line 15, in <module>
                                                       from .urls import trackers, hosters, get_urls, update_urls, deprioritize_url
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/urls.py", line 73, in <module>
                                                       trackers = _get_urls_in_array_format(trackers_config)
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/urls.py", line 65, in _get_urls_in_array_format
                                                       cached_urls = _get_cached_urls(scraper)
                                                     File "/storage/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/urls.py", line 21, in _get_cached_urls
                                                       cache_result = database.cache_get(cache_key)
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/database.py", line 14, in cache_get
                                                       return g.CACHE.get(key)
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/database/cache/__init__.py", line 149, in get
                                                       result, expires = self._db_cache.get(cache_id, checksum)
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/database/cache/__init__.py", line 281, in get
                                                       cache_data = self.execute_sql(query, (cache_id,)).fetchone()
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 228, in execute_sql
                                                       return self._execute_query(data, connection.cursor(), query)
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 178, in _execute_query
                                                       result = cursor.execute(query, data)
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 81, in _loads
                                                       return pickle.loads(value)
                                                   _pickle.UnpicklingError: invalid load key, '['.
                                                   -->End of Python script error report<--

**Comment by sabatale** [comment]
I can confirm I have the same issue with the latest version.
