### ISSUE TITLE
[BUG] Real debrid not authorizing

### ISSUE THREAD

**Issue by deanwethers** [nixgates/plugin.video.seren#627]
**Describe the bug**
When entering in seren Real Debrid authorization code the popup doesn't go away and nothing happens and no playable sources found for all movies and shows. On the real debrid website it shows the code was successfully completed and it's added under devices. Authorizing trakt works fine as well.

**To Reproduce**
1. Go to 'accounts'
2. Click on 'authorize real debrid'
3. Enter real debrid Auth code.
4. See popup that doesn't go away and real debrid still is unauthorized.

**Expected behavior**
For real debrid to be authorized.
**Screenshots**
![image](https://user-images.githubusercontent.com/84949476/122604268-4c7f6f80-d03b-11eb-9840-ed209d0e94c0.jpeg)
![image](https://user-images.githubusercontent.com/84949476/122604776-20182300-d03c-11eb-8e99-359c7e32776f.png)
![image](https://user-images.githubusercontent.com/84949476/122605454-17741c80-d03d-11eb-8a1b-0fe99837702a.jpeg)
![image](https://user-images.githubusercontent.com/84949476/122605474-1e9b2a80-d03d-11eb-8621-907da76e45e5.jpeg)

**Kodi Version (please complete the following information):**
 - Kodi Version 19.1

**Additional context**
This was not an issue prior to the new update. Of course the other issue was Real debrid expired even when it's not expired but now I can't even authorize my real debrid to get it working after 2.1.1

**Comment by sinanawad** [comment]
+1, would logs additional logs help?

**Comment by drinfernoo** [comment]
Real-Debrid authorization issues were fixed in 2.1.1... If you're still having issues, we'll need a full debug log.

Failing that, a fresh install of Seren (uninstall Seren, remove add-on data, and reinstall Seren) may be required.

**Comment by maxpower742** [comment]
I don't know how to provide a log, sorry. But I've just done a fresh install as @drinfernoo said, and that seems to have resolved it.

**Comment by drinfernoo** [comment]
For what it's worth, clearing Seren's cache may be enough to sidestep this issue, rather than a full reinstall.

**Comment by deanwethers** [comment]
> For what it's worth, clearing Seren's cache may be enough to sidestep this issue, rather than a full reinstall.

I tried cache clear and didn't fix it. Must need a fresh install

**Comment by maxpower742** [comment]
Yeah I'm pretty sure I tried a cache clear as well without success, before re-installing.

**Comment by cphilpotts** [comment]
> Real-Debrid authorization and expiration issues were fixed in 2.1.1... If you're still having issues, we'll need a full debug log.
> 
> Failing that, a fresh install of Seren (uninstall Seren, remove add-on data, and reinstall Seren) may be required.

I’m having same issue. Here’s my log. 

https://paste.kodi.tv/alidosasuf

**Comment by cphilpotts** [comment]
> > Real-Debrid authorization and expiration issues were fixed in 2.1.1... If you're still having issues, we'll need a full debug log.
> > Failing that, a fresh install of Seren (uninstall Seren, remove add-on data, and reinstall Seren) may be required.
> 
> I’m having same issue. Here’s my log.
> 
> https://paste.kodi.tv/alidosasuf

After 2 cycles of uninstall, reboot, re-install and then about a dozen retries of authorizing Trakt and RD it finally seems to be working again. Will see if it’s still working tomorrow.

**Comment by deanwethers** [comment]
> > > Real-Debrid authorization and expiration issues were fixed in 2.1.1... If you're still having issues, we'll need a full debug log.
> 
> > > Failing that, a fresh install of Seren (uninstall Seren, remove add-on data, and reinstall Seren) may be required.
> 
> > 
> 
> > I’m having same issue. Here’s my log.
> 
> > 
> 
> > https://paste.kodi.tv/alidosasuf
> 
> 
> 
> After 2 cycles of uninstall, reboot, re-install and then about a dozen retries of authorizing Trakt and RD it finally seems to be working again. Will see if it’s still working tomorrow. 

Yep I can confirm as well that full deletion of seren and the settings and a fresh install now let's me authorize RD and the popup goes away successfully.

**Comment by deanwethers** [comment]
> > > > Real-Debrid authorization and expiration issues were fixed in 2.1.1... If you're still having issues, we'll need a full debug log.
> > 
> > > > Failing that, a fresh install of Seren (uninstall Seren, remove add-on data, and reinstall Seren) may be required.
> > 
> > > 
> > 
> > > I’m having same issue. Here’s my log.
> > 
> > > 
> > 
> > > https://paste.kodi.tv/alidosasuf
> > 
> > 
> > 
> > After 2 cycles of uninstall, reboot, re-install and then about a dozen retries of authorizing Trakt and RD it finally seems to be working again. Will see if it’s still working tomorrow. 
> 
> Yep I can confirm as well that full deletion of seren and the settings and a fresh install now let's me authorize RD and the popup goes away successfully. 

I take that back... Needed to re Auth seren and now popup won't go away again..

**Comment by deanwethers** [comment]
Here's my log

https://paste.kodi.tv/harazoqari

**Comment by deanwethers** [comment]
I've reinstalled seren from scratch 2 times now and still having issues re authorizing RD. Not sure what else to try at this point. Just going to use Premiumize until a solution is found. Not sure if this is a wide spread issue or not but seems a few others have the problem?

**Comment by drinfernoo** [comment]
@deanwethers, The error code in your log indicates a `Permission Denied` response from RD... which likely means something is wrong with your account, and is not the same thing as what is happening to others in this issue.

**Comment by BinaryAssault** [comment]
I can pull a log as well, but I am having the same issue. RD works in other add-ons. Not using a VPN. Confirmed started happening with 2.1.1

**Comment by deanwethers** [comment]
> @deanwethers, The error code in that log indicates a `Permission Denied` response from RD... which likely means something is wrong with your account, and is not the same thing as the original issue that you opened.  
> 
> EDIT: Are you using a VPN? @cphilpotts, Same question.

@drinfernoo yes I'm using nordvpn. For some reason I just can't get real debrid to authorize, the popup with the code won't go away this issue started with 2.1.1. So I resorted to premiumize which worked for one episode and when I clicked next up it throws this popup now even though when I go into seren settings it shows premiumize is authorized and my account info. The only way I get RD to authorize correctly and the popup goes away is to do a fresh seren install but then after a few hours it says failed to refresh RD token and when I try to authorize again I have the same issue with the popup not going away hence it won't authorize![image](https://user-images.githubusercontent.com/84949476/122659303-6654ab80-d13c-11eb-8f47-15d9de61031c.jpeg)

**Comment by deanwethers** [comment]
> > @deanwethers, The error code in that log indicates a `Permission Denied` response from RD... which likely means something is wrong with your account, and is not the same thing as the original issue that you opened.  
> > 
> > EDIT: Are you using a VPN? @cphilpotts, Same question.
> 
> @drinfernoo yes I'm using nordvpn. For some reason I just can't get real debrid to authorize, the popup with the code won't go away this issue started with 2.1.1. So I resorted to premiumize which worked for one episode and when I clicked next up it throws this popup now even though when I go into seren settings it shows premiumize is authorized and my account info. The only way I get RD to authorize correctly and the popup goes away is to do a fresh seren install but then after a few hours it says failed to refresh RD token and when I try to authorize again I have the same issue with the popup not going away hence it won't authorize![image](https://user-images.githubusercontent.com/84949476/122659303-6654ab80-d13c-11eb-8f47-15d9de61031c.jpeg)

@drinfernoo well I figured out the issue to that popup but not exactly what caused it. Still can't authorize RD.. Again I can confirm on real debrid itself it says success and the device is added but the popup won't go away with the code. 

However my accounts section is completely cleared out now after I just reconnected my trakt and premiumize and proceeded to watch an episode now they are all blank again?. ![image](https://user-images.githubusercontent.com/84949476/122659348-e713a780-d13c-11eb-9b3f-7a56b3c5e012.jpeg)

**Comment by ivarbrandt** [comment]
I had this issue as well even with a fresh install of Seren. What worked for me was uninstalling the Nixgates repo, but leave Seren installed. Then reinstall the repo from the zip. It will tell you that there is an update for the repo available (if you have automatic updates disabled in Kodi). Update the repo, and then update Seren. Your settings will be reset but if you had the A4kScrapers already installed, those will stay through the update. You should now be able to authorize RD and Trakt. If you have a VPN, make sure it is off when authorizing.

**Comment by deanwethers** [comment]
@ivarbrandt my repo and seren are already up to date. The issue has something to do with RD authentication within seren. 

When I do a fresh install it authorizes fine the first time then after an hour or two when I reload skin it says "failed to reauth Rd token please manually authorize" so I attempt to enter the Auth code on screen again and then the popup never goes away. 

I've reinstalled 3 times now... Also Now I'm dealing with another issue where after I authenticate trakt, premiumize, and RD on a fresh install, after a few episodes played it says I have no debrid accounts setup, when I go to seren settings all of my accounts are gone after I just reconnected them.. This has happened 2 times now and I can't figure it out so I give up for now. Lol

**Comment by ivarbrandt** [comment]
@deanwethers 

I get your frustration. It's not about it being up to date tho. Did you uninstall the repo? Then reinstall the repo, update the repo, and reinstall Seren? If that didn't work just downgrade to 2.0.19.

**Comment by drinfernoo** [comment]
There is no point in reinstalling the repo... it will deliver the exact same assets no matter how many times you install it.

**Comment by deanwethers** [comment]
@ivarbrandt I would downgrade to 2.0.19 but I'm not sure how to roll back. I don't have any backups with That version. Is there a zip file url I can install from?

**Comment by ivarbrandt** [comment]
Reinstalling the repo worked for me. Guess I got lucky.

@drinfernoo Is it cool with you if I post a zip here of 2.0.19 for @deanwethers ?

**Comment by drinfernoo** [comment]
Zips are publicly available through the GitHub repo, so that should not be necessary. Also, we don't support previous versions, so if other issues arise (they will, since the 2.1.0 and 2.1.1 updates changed a good portion of the Trakt database), we will not support it.

This issue is being looked at, but we're not really sure what's going on. Have patience, and realize that there's probably better things to do than watch Kodi for a day or two 😉

**Comment by drinfernoo** [comment]
I can confirm this has been fixed in dev... should be working in the next update :+1:

**Comment by drinfernoo** [comment]
https://redd.it/o8ppa5

**Comment by drinfernoo** [comment]
This should be fixed in 2.1.2.

**Comment by deanwethers** [comment]
@drinfernoo confirmed this is fixed now with 2.1.2 thanks!

**Comment by deanwethers** [comment]
> @drinfernoo confirmed this is fixed now with 2.1.2 thanks!

However now I get playback failed on everything I click. I tried clear cache and reload but still happening. My RD is authorized now however and Premiumize. Any suggestions?

**Comment by drinfernoo** [comment]
@deanwethers That may be a separate issue, but I can't really see anything going away on your log.

I'm gonna close this one.
