### ISSUE TITLE
[BUG]Scraping Failure (Xbox)

### ISSUE THREAD

**Issue by Cwoo0** [nixgates/plugin.video.seren#780]
**Describe the bug**

I have been having this issue for a while now, tried out the new version and the issue is still there. I don't believe that there was a Seren or a Kodi update that broke the add-on for me, so I think it must have been a dependency or a providers update that broke it. 

Possibly Xbox specific as I have not seen anyone else talk about this. 

I get a Seren error popup on kodi start.

Basically whenever I try to watch something it gets stuck at "initializing providers" sometimes it scrapes the first couple providers and then stalls. When this happens I see the number of torrents found jump up from 0 one or two times and then it just stops scraping. Torrents found no longer counts up and providers remaining stops counting down. 

Even when it does scrape some of the providers and shows that there were torrents found, I always get the no sources found message after scraping times out. It never gets far enough to compare the found torrents to RD cache. 

Here is a debug log, with all providers enabled, this time it just sat on the "Initializing Providers" screen, I let it run for a few minutes before closing Kodi.

**Log**

https://paste.kodi.tv/majoyasolu

**To Reproduce**

Try and scrape any item. 

**Environment**

 - Operating System: Xbox (Windows 10.0.22621.1556)
 - Kodi Version: 19.4
 - Seren Version: 2.2.0

**Comment by drinfernoo** [comment]
The error you're getting is related to our update checker:
```python
2022-06-02 12:03:41.276 T:3904    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '>' not supported between instances of 'str' and 'NoneType'
                                                   Traceback (most recent call last):
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.seren\service.py", line 40, in <module>
                                                       do_update_news()
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.seren\resources\lib\modules\update_news.py", line 22, in do_update_news
                                                       for msg in [
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.seren\resources\lib\modules\update_news.py", line 25, in <listcomp>
                                                       if v > last_update_news_version
                                                   TypeError: '>' not supported between instances of 'str' and 'NoneType'
                                                   -->End of Python script error report<--
```
And doesn't really have anything to do with scraping or providers 😅

In any case, we've already fixed it in 2.2.1.

**Comment by Cwoo0** [comment]
> The error you're getting is related to our update checker:
> ```python
> 2022-06-02 12:03:41.276 T:3904    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'TypeError'>
>                                                    Error Contents: '>' not supported between instances of 'str' and 'NoneType'
>                                                    Traceback (most recent call last):
>                                                      File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.seren\service.py", line 40, in <module>
>                                                        do_update_news()
>                                                      File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.seren\resources\lib\modules\update_news.py", line 22, in do_update_news
>                                                        for msg in [
>                                                      File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.seren\resources\lib\modules\update_news.py", line 25, in <listcomp>
>                                                        if v > last_update_news_version
>                                                    TypeError: '>' not supported between instances of 'str' and 'NoneType'
>                                                    -->End of Python script error report<--
> ```
> And doesn't really have anything to do with scraping or providers 😅
> 
> In any case, we've already fixed it in 2.2.1.

I'm not sure the update checker error is causing the problem I am having as I have the same scraping issue on the previous version of Seren. That version opens a popup saying that there is no inbuilt version checker after install.

If I roll back to version 2.1.9 I no longer get the Seren error popup on Kodi start or the entry you quoted in the Log file but I am still not able to scrape or play anything.

Trying to play anything stalls on the "Starting Engines" screen.

It just seemed to break out of the blue a few months back, no Seren or Kodi update, if I remember correctly, it just stopped scraping one day. 

Here is a debug log of the same issue occuring on Seren version 2.1.9, without the update checker error you mentioned.



Log: https://paste.kodi.tv/esicinihis

**Comment by Cwoo0** [comment]
Just tried Seren version 2.2.1, that fixed the error popup and the error in the log that you previously quoted but unfortunately I still cannot scrape or play anything.

Stalls on "initializing Providers" and then I'm stuck on that screen untill I force close Kodi. 

Version 2.2.1 log:

https://paste.kodi.tv/onufehaven

**Comment by cbizzle14** [comment]
I am on Xbox and have no issues. Currently watching a show now. Are you sure a4kscrapers are installed and/or updated?

**Comment by Cwoo0** [comment]
> I am on Xbox and have no issues. Currently watching a show now. Are you sure a4kscrapers are installed and/or updated?

Yup, installed from the URL, currently showing version 2.76.0

What Xbox do you have? 

I'm using a Series X and just can't get it to work at all, have tried fresh Kodi install a couple times now but always the same thing. Never scrapes and no obvious errors in the log. It just locks up.

**Comment by cbizzle14** [comment]
Weird. I have series X as well. Same version of scrapers too. Have you tried a hard reset of your Xbox, hold the power button on the console for 10 seconds?

**Comment by Cwoo0** [comment]
> Weird. I have series X as well. Same version of scrapers too. Have you tried a hard reset of your Xbox, hold the power button on the console for 10 seconds? 

Yup tried that too, I even tried factory resetting my console completely and starting with a fresh install of Kodi but the issue remains. 

All other add-ons work fine, but for some reason Seren just won't scrape. Very confusing as it doesn't even have any error popups in Kodi or show any obvious problems in the Log or even a debug log, it just seems to stop in its tracks as soon as I try and scrape anything. 

The only thing I can think of now is maybe it's because I am on Alpha Skip ahead software but even then this issue started for me months ago so any changes to the Xbox OS should have made it to out to the public builds by now.

**Comment by cbizzle14** [comment]
Are you using premiumize as your debrid service?

**Comment by Cwoo0** [comment]
> Are you using premiumize as your debrid service?

Nope, I use Real debrid.

**Comment by Meese77** [comment]
I was hoping this may have been resolved in the latest version, but still persists unfortunately.

**Comment by Cizzurp215** [comment]
been having the same issue for a few months now. There was a reddit thread about it also - https://www.reddit.com/r/Addons4Kodi/comments/xopi1u/seren_not_behaving_on_xbox_series_x/

I thought the update to 3.0 or even the kodi update to 20 would fix but still it's not finding any sources. I have a4k installed. I've done all the wipes and such. Seren runs perfectly on my windows laptop and on my fire tv. I prefer using my series x because the speed and picture are superior but it looks like I won't be able to any time soon. I hope the issue gets resolved soon
