### ISSUE TITLE
[BUG] Seren doesn't send watched status to Trakt

### ISSUE THREAD

**Issue by StanLee01** [nixgates/plugin.video.seren#829]
**Describe the bug**
When you watch a show, normally it sends the watched status to Trakt. This doesn't happen since the new update. It does send the rating through the Trakt add-on to trakt tho. 

**Kodi Version:
 - Kodi Version 19.4
 - Seren Version 2.2.2
 - nVidia Shield

**Comment by drinfernoo** [comment]
Please attach a debug log.

**Comment by StanLee01** [comment]
https://paste.kodi.tv/dofojunami

Here you go. 

Maybe good to know, that I see no watched status on my Trakt app but I do see the rating I gave it after I watched it on Seren. I even can see that I'm watching it on the app. But somehow it doesn't mark it as watched. 

An other issue is that it doesn't activate the next-up dialog pop-up for the next episode, however it does automatically starts searching for providers after the episode.

**Comment by dplim87** [comment]
On a related note, I believe this same bug is the reason pre-emptive scraping is also not working since the release of 2.2.2.

**Comment by eengert** [comment]
Not sure if this is helpful, but I think that Seren 2.2.2 does mark episodes as watched in Trakt if it's the last available episode.  I just watched an episode of a show that is the most recently released episode, and it got marked as watched and disappeared from my widget.  Then I watched a different show that still has many episodes remaining and the episode I watched did not get marked as watched in Trakt and I had to do it manually.

**Comment by c1bear** [comment]
Im getting this pop up I click yes and Seren not marking it as watched and it replays the same episode i just watched  
![20221031_165402](https://user-images.githubusercontent.com/117225832/199337678-e197d0e3-2f7d-4dd0-b25e-500e27a6f11b.jpg)

**Comment by StanLee01** [comment]
> Im getting this pop up I click yes and Seren not marking it as watched and it replays the same episode i just watched  
> 
> ![20221031_165402](https://user-images.githubusercontent.com/117225832/199337678-e197d0e3-2f7d-4dd0-b25e-500e27a6f11b.jpg)
> 
> 

I've got the same issue.

**Comment by dplim87** [comment]
Yeah I'm not sure what's going on. The commit I made seemed to have worked, except now everything seems to be working except now it seems the "scrobble/stop" POST is failing due to the connection being reset by peer.

**Comment by MikeTosen** [comment]
Can confirm,  having exactly same problem.
All shows that i am in the middle of, does this.

**Comment by StanLee01** [comment]
> Not sure if this is helpful, but I think that Seren 2.2.2 does mark episodes as watched in Trakt if it's the last available episode.  I just watched an episode of a show that is the most recently released episode, and it got marked as watched and disappeared from my widget.  Then I watched a different show that still has many episodes remaining and the episode I watched did not get marked as watched in Trakt and I had to do it manually.

For me, both don't work.

**Comment by drinfernoo** [comment]
@dplim87 That looks like a fix to me! Working in getting that one into a public release 🙏

**Comment by drinfernoo** [comment]
This one should be fixed in 2.2.3!

**Comment by StanLee01** [comment]
I can confirm that the watching the last episode, is being marked as watched and the data is send to Trakt. 

I'll test the "next up" pop-up too and let you know.

**Comment by c1bear** [comment]
I'm still getting the same error message / pop-up not marked as watched,
but now at least when I click yes its marking as watched
