### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rjh700** [nixgates/plugin.video.seren#956]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1]

**Additional context**

**Comment by rjh700** [comment]
Seren can’t find playable sources. Trackt and Real Debrid are up to date and authorized. I have 2 completely separate systems, one with Kodi 19xx and one with latest kodi Omega on 4 K fire stick. Both stopped finding playable sources at the same time. Both have latest Seren and A4Kscrapers. I have returned Firestick to factory settings and reloaded all several times. Any ideas?  Thanks.

**Comment by henryjfry** [comment]
Look at some of the other recent bugs, this has been fixed by a different seren version 3.0.0.6

**Comment by rjh700** [comment]
Thanks. I’ll try it. Sent from my iPhoneOn Dec 22, 2024, at 5:03 PM, henryjfry ***@***.***> wrote:﻿
Look at some of the other recent bugs, this has been fixed by a different seren version 3.0.0.6

**Comment by rjh700** [comment]
I have 3.1.1 already but, since you were nice enough to answer, just nuked Seren and a4kscrapers and reinstalled them. Still no luck. Thanks. Sent from my iPhoneOn Dec 22, 2024, at 5:03 PM, henryjfry ***@***.***> wrote:﻿
Look at some of the other recent bugs, this has been fixed by a different seren version 3.0.0.6

**Comment by cgwprs** [comment]
@rjh700 
where did you find a Seren version 3.1.1 ? I have the bbviking/Seren verion 3.0.62 as being the most recent. Also, i dont know version 3.0.0.6, I am assuming this is a typo.

**Comment by henryjfry** [comment]
Oh yeah that was a typo, I meant the biking version
